# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChurchM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetails',
            name='account_balance',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='accountdetails',
            name='account_number',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='accountdetails',
            name='account_sort_code',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='bank_phone',
            field=models.PositiveIntegerField(),
        ),
    ]
