# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChurchM', '0002_auto_20170916_0327'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Funds',
            new_name='Fund',
        ),
        migrations.AlterModelOptions(
            name='accountdetails',
            options={'verbose_name_plural': 'Account Details'},
        ),
        migrations.AlterModelOptions(
            name='bankdetails',
            options={'verbose_name_plural': 'Bank Details'},
        ),
        migrations.AlterModelOptions(
            name='biblereading',
            options={'verbose_name_plural': 'Bible Readings'},
        ),
        migrations.AlterModelOptions(
            name='donation',
            options={'verbose_name_plural': 'Donations'},
        ),
        migrations.AlterModelOptions(
            name='household',
            options={'verbose_name_plural': 'Households'},
        ),
        migrations.AlterModelOptions(
            name='ministry',
            options={'verbose_name_plural': 'Ministries'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='bank_add',
            field=models.TextField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='bank_phone',
            field=models.CharField(max_length=10),
        ),
    ]
