# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChurchM', '0004_auto_20170916_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='house_address',
            field=models.TextField(blank=True, max_length=256),
        ),
    ]
