# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChurchM', '0005_people_house_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Event Types',
            },
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
