# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChurchM', '0006_auto_20170916_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='Remarks',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='event_type',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
