# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ChurchM', '0007_auto_20170916_0551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField()),
                ('Remarks', models.CharField(blank=True, max_length=256)),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChurchM.EventType')),
            ],
            options={
                'verbose_name_plural': 'Events',
            },
        ),
    ]
