# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 10:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChurchM', '0008_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BibleReading',
        ),
    ]
