# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChurchM', '0009_delete_biblereading'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_end_time',
            field=models.TimeField(default='12:00 AM'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_time_start',
            field=models.TimeField(default='12:00 AM'),
        ),
    ]
