# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ChurchM', '0010_auto_20170916_0608'),
    ]

    operations = [
        migrations.CreateModel(
            name='BibleReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bible_text', models.CharField(max_length=80)),
                ('Remarks', models.CharField(blank=True, max_length=256)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChurchM.Event')),
            ],
            options={
                'verbose_name_plural': 'Bible Readings',
            },
        ),
    ]
