# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ChurchM', '0011_biblereading'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adult_male', models.IntegerField(blank=True)),
                ('adult_female', models.IntegerField(blank=True)),
                ('youth_male', models.IntegerField(blank=True)),
                ('youth_female', models.IntegerField(blank=True)),
                ('young_adults_male', models.IntegerField(blank=True)),
                ('young_adults_female', models.IntegerField(blank=True)),
                ('children', models.IntegerField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChurchM.Event')),
            ],
            options={
                'verbose_name_plural': 'Attendance',
            },
        ),
        migrations.AlterField(
            model_name='people',
            name='lastname',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
