# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChurchM', '0012_auto_20170916_0906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donationtype',
            options={'verbose_name_plural': 'Donations Type'},
        ),
        migrations.AddField(
            model_name='attendance',
            name='total_attendance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendance',
            name='total_female',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendance',
            name='total_male',
            field=models.IntegerField(default=0),
        ),
    ]
