# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChurchM', '0013_auto_20170916_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_time_start',
            field=models.TimeField(),
        ),
    ]
